apiVersion: v1
kind: Pod
metadata:
  name: sample-app
spec:
  containers:
  - name: sample-app
    image: dev-image:latest
    envFrom:
    - configMapRef:
        name: dev
    env:
      - name: MYSQL_ROOT_PASSWORD
        valueFrom: 
         secretKeyRef:
          name: dev-secret 
          key: password
    ports:
      - name: tcp
        protocol: TCP
        containerPort: 80